[theme]
primaryColor = "#9b59b6" # A muted purple

backgroundColor = "#1e1e1e" # Dark grey, almost black

secondaryBackgroundColor = "#2c2c2c" # Slightly lighter dark grey

textColor = "#fafafa" # Off-white/very light grey for good contrast
font = "sans serif"

[server]
maxUploadSize = 10
headless = true

[client]
showWarningOnDirectExecution = false
gatherUsageStats = true

[logger]
level = "INFO"

[deprecation]
showPyplotGlobalUse = false
